apiVersion: v1
kind: Namespace
metadata:
  name: internship-app
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: internship-app
type: Opaque
stringData:
  PROJECT_NAME: "Internship Project"
  SECRET_KEY: "CHANGE_ME_SECRET_KEY"
  DOMAIN: "localhost"
  ENVIRONMENT: "production"
  POSTGRES_SERVER: "db-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_ME_POSTGRES_PASSWORD"
  POSTGRES_DB: "app"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "CHANGE_ME_SUPERUSER_PASSWORD"
